name: MATLAB | Windows Mac Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Run MATLAB Tests on GitHub-Hosted Runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
            
      - name: Update and install Python packages
        run: |
            python -m pip install --upgrade pip wheel
            python -m pip install mhkit --upgrade
            python -m pip install --upgrade h5py==2.7
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: mhkit; mhkit_python_utils; examples/data
          select-by-tag: DebuggingActions
          test-results-junit: mhkit/tests/results.xml
          code-coverage-cobertura: mhkit/tests/results.xml
