name: Run MATLAB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest] # windows-latest
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    env:
      mhkit-python-dir: 'MHKiT-Python'
    steps:
      - name: Check out MHKiT-MATLAB
        uses: actions/checkout@v2
      - name: Check out MHKiT-Python
        uses: actions/checkout@v2
        with:
          repository: 'MHKiT-Software/MHKiT-Python'
          path: ${{env.mhkit-python-dir}}
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mhkit module (from source)
        run: python -m pip install -e . "matplotlib<3.4.2"
        working-directory: ${{env.mhkit-python-dir}}
      - name: Install mhkit-python-utils module
        run: python -m pip install -e .
      - name: Create MATLAB batch command
        shell: bash
        run: echo "COMMAND=pyenv('ExecutionMode', 'OutOfProcess'), 
                           version, 
                           addpath(genpath('mhkit')), 
                           import matlab.unittest.TestSuite, 
                           import matlab.unittest.TestRunner, 
                           testFolder = ['mhkit' filesep 'tests'], 
                           suite = TestSuite.fromFolder(testFolder), 
                           runner = TestRunner.withTextOutput,
                           results = runner.run(suite), 
                           assertSuccess(results)" >> "$GITHUB_ENV"
      - name: Install and test MHKiT-MATLAB
        run: matlab -batch "${{ env.COMMAND }}"

